site_name: Zequn's Wiki Site

nav:
  - 主页: index.md
  - Lammps: lammps.md
  - VMD: VMD.md
  - Linux: Linux.md
  - Python: Python.md
  - Github: Github.md
  - 一些代码: Bat.md
  - 一些想法: Figures.md
theme:
  name: readthedocs #'readthedocs'默认
  logo: 'images/a4x2g-r195l.svg'